const cardsNoFee = [
    {
        "dining": "0",
        "grocery": "5",
        "retail": "0",
        "cardName": "Discover It Cash Back",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Discover",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Grocery for Q1 2019",
        "total": "1",
        "bonusType": "variable",
        "id": "1",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Discover Gas and Restaurant",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Discover",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1",
        "bonusType": "variable",
        "id": "2",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Discover Travel",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Discover",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1.5",
        "bonusType": "variable",
        "id": "3",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Chase Freedom",
        "bonus": "150",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "5",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Chase",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Gas for Q1 2019",
        "total": "1",
        "bonusType": "fixed",
        "id": "4",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Chase Freedom Unlimited",
        "bonus": "200",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Chase",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1.5",
        "bonusType": "fixed",
        "id": "5",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "3",
        "retail": "0",
        "cardName": "Chase Amazon Visa",
        "bonus": "50",
        "hasAnnualFee": "0",
        "online": "3",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Chase",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Groceries must be Whole Foods, online must be Amazon",
        "total": "1",
        "bonusType": "fixed",
        "id": "6",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Capital One Quicksilver",
        "bonus": "150",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1.5",
        "bonusType": "fixed",
        "id": "7",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Capital One VentureOne Rewards",
        "bonus": "200",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "10",
        "notes": "Travel only at Hotels.com, assume half travel spend on hotels",
        "total": "1.25",
        "bonusType": "fixed",
        "id": "8",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "3",
        "grocery": "2",
        "retail": "0",
        "cardName": "Capital One SavorOne",
        "bonus": "150",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "3",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1",
        "bonusType": "fixed",
        "id": "9",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "2",
        "retail": "0",
        "cardName": "Capital One Platinum Preferred",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1",
        "bonusType": "fixed",
        "id": "10",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Bank of America Travel Rewards",
        "bonus": "250",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Bank of America",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1.5",
        "bonusType": "fixed",
        "id": "11",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "2",
        "retail": "0",
        "cardName": "Bank of America Cash Rewards",
        "bonus": "200",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "3",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Bank of America",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1",
        "bonusType": "fixed",
        "id": "12",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Citi Double Cash",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Citi",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "2",
        "bonusType": "fixed",
        "id": "13",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "2",
        "retail": "0",
        "cardName": "Citi American Airlines Aadvantage MileUp",
        "bonus": "150",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "American",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Travel must be through AA",
        "total": "1",
        "bonusType": "fixed",
        "id": "14",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "3",
        "retail": "0",
        "cardName": "Blue Cash Everyday (AMEX)",
        "bonus": "150",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "American Express",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "1",
        "bonusType": "fixed",
        "id": "15",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Blue Delta SkyMiles (AMEX)",
        "bonus": "100",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Delta",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Travel must be through Delta",
        "total": "1",
        "bonusType": "fixed",
        "id": "16",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Fidelity Rewards Visa Signature",
        "bonus": "0",
        "hasAnnualFee": "0",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Fidelity",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "",
        "total": "2",
        "bonusType": "fixed",
        "id": "17",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "4",
        "grocery": "0",
        "retail": "0",
        "cardName": "Uber Visa",
        "bonus": "100",
        "hasAnnualFee": "0",
        "online": "2",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "Uber",
        "cardType": "",
        "other": "2",
        "annualFee": "0",
        "lodging": "3",
        "notes": "",
        "total": "1",
        "bonusType": "fixed",
        "id": "18",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Chase Sapphire Preferred",
        "bonus": "595",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Chase Preferred",
        "cardType": "",
        "other": "2",
        "annualFee": "95",
        "lodging": "2",
        "notes": "Bonus when spend $4,000 in 3 months; $95 fee waived first yr",
        "total": "1",
        "bonusType": "",
        "id": "19",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "3",
        "grocery": "0",
        "retail": "0",
        "cardName": "Chase Sapphire Reserve",
        "bonus": "500",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "Chase Reserve",
        "cardType": "",
        "other": "3",
        "annualFee": "150",
        "lodging": "3",
        "notes": "Bonus when spend $4,000 in 3 months; $450 fee w/ $300 credit",
        "total": "1",
        "bonusType": "",
        "id": "20",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Southwest Rapid Rewards Plus",
        "bonus": "600",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Southwest",
        "cardType": "",
        "other": "0",
        "annualFee": "39",
        "lodging": "0",
        "notes": "Bonus when spend $12,000 first year; $69 fee w/ $30 credits",
        "total": "1",
        "bonusType": "",
        "id": "21",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Southwest Rapid Rewards Premier",
        "bonus": "600",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Southwest",
        "cardType": "",
        "other": "0",
        "annualFee": "39",
        "lodging": "0",
        "notes": "Bonus when spend $12,000 first year; $99 fee w/ $60 credits",
        "total": "1",
        "bonusType": "",
        "id": "22",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Southwest Rapid Rewards Priority",
        "bonus": "600",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Southwest",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Bonus when spend $12,000 first year; $150 fee w/ $150 credits",
        "total": "1",
        "bonusType": "",
        "id": "23",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "United Explorer",
        "bonus": "745",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "United",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "2",
        "notes": "Bonus when spend $10,000 in 6 months; $95 fee waived first yr",
        "total": "1",
        "bonusType": "",
        "id": "24",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "United MileagePlus Club",
        "bonus": "500",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "United",
        "cardType": "",
        "other": "0",
        "annualFee": "450",
        "lodging": "0",
        "notes": "Bonus when spend $3,000 in 3 months; $450 fee w/ $550 United Club credit. Assumes travel = United",
        "total": "1.5",
        "bonusType": "",
        "id": "25",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "British Airways Visa Signature",
        "bonus": "1000",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "British ",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "0",
        "notes": "Bonus when spend $20,000 first year; Assumes travel = British Airways",
        "total": "1",
        "bonusType": "",
        "id": "26",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Marriott Rewards Premier Plus",
        "bonus": "750",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Marriott",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "6",
        "notes": "Bonus when spend $3,000 in 3 months; $95 fee offset by free night",
        "total": "2",
        "bonusType": "",
        "id": "27",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "The World of Hyatt",
        "bonus": "600",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Hyatt",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "4",
        "notes": "Bonus when spend $6,000 in 6 months; $95 fee offset by free night",
        "total": "1",
        "bonusType": "",
        "id": "28",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "2",
        "retail": "0",
        "cardName": "IHG Rewards Club Premier",
        "bonus": "800",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "IHG",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "10",
        "notes": "Bonus when spend $2,000 in 3 months; $89 fee offset by free night",
        "total": "1",
        "bonusType": "",
        "id": "29",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "4",
        "grocery": "2",
        "retail": "0",
        "cardName": "Capital One Savor Rewards",
        "bonus": "595",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "4",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "0",
        "notes": "Bonus when spend $3,000 in 3 months; $95 fee waived first yr",
        "total": "1",
        "bonusType": "",
        "id": "30",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Capital One Venture Rewards",
        "bonus": "595",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Capital One",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "10",
        "notes": "Bonus when spend $3,000 in 3 months; $95 fee waived first yr",
        "total": "2",
        "bonusType": "",
        "id": "31",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Bank of America Premium Rewards",
        "bonus": "500",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Bank of America",
        "cardType": "",
        "other": "2",
        "annualFee": "-5",
        "lodging": "2",
        "notes": "$95 fee w/ $100 credit; Bonus when spend $3,000 in 3 months",
        "total": "1.5",
        "bonusType": "",
        "id": "32",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Alaska Airlines Visa",
        "bonus": "300",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "Alaska",
        "cardType": "",
        "other": "0",
        "annualFee": "75",
        "lodging": "0",
        "notes": "Bonus when spend $1,000 in 3 months; $75 fee w/ 1 free companion flight ($300) w/ $99 fee",
        "total": "1",
        "bonusType": "",
        "id": "33",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Spirit Airlines World Mastercard",
        "bonus": "359",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Spirit",
        "cardType": "",
        "other": "0",
        "annualFee": "9",
        "lodging": "0",
        "notes": "Bonus when spend $500 in 3 months; $59 fee w/ $50 credit",
        "total": "2",
        "bonusType": "",
        "id": "34",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Virgin Atlantic",
        "bonus": "200",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "Virgin",
        "cardType": "",
        "other": "0",
        "annualFee": "90",
        "lodging": "0",
        "notes": "Bonus after first purchase",
        "total": "1.5",
        "bonusType": "",
        "id": "35",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Citi AAdvantage Platinum Select World Elite Mastercard",
        "bonus": "599",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "2",
        "affiliation": "American",
        "cardType": "",
        "other": "0",
        "annualFee": "-1",
        "lodging": "0",
        "notes": "Bonus when spend $6,000 in 12 months; $99 fee w/ $100 annual flight credit ($20,000 purchases)",
        "total": "1",
        "bonusType": "",
        "id": "36",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "Citi AAdvantage Executive World Elite Mastercard",
        "bonus": "500",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "American",
        "cardType": "",
        "other": "0",
        "annualFee": "450",
        "lodging": "0",
        "notes": "Bonus when spend $5,000 in 3 months; Admiral Lounge Access",
        "total": "1",
        "bonusType": "",
        "id": "37",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "2",
        "grocery": "0",
        "retail": "0",
        "cardName": "Citi Premier",
        "bonus": "595",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "3",
        "entertainment": "2",
        "air": "3",
        "affiliation": "Citi",
        "cardType": "",
        "other": "3",
        "annualFee": "95",
        "lodging": "3",
        "notes": "Bonus when spend $4,000 in 3 months;",
        "total": "1",
        "bonusType": "",
        "id": "38",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "4",
        "grocery": "4",
        "retail": "0",
        "cardName": "American Express Gold",
        "bonus": "350",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "American Express",
        "cardType": "",
        "other": "0",
        "annualFee": "30",
        "lodging": "0",
        "notes": "Bonus when spend $2,000 in 3 months; $250 fee w/ $220 in annual credits (grocery, air)",
        "total": "1",
        "bonusType": "",
        "id": "39",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Platinum",
        "bonus": "600",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "5",
        "affiliation": "American Express",
        "cardType": "",
        "other": "0",
        "annualFee": "150",
        "lodging": "5",
        "notes": "Bonus when spend $5,000 in 3 months; $550 fee w/ $400 in annual credits (uber, air)",
        "total": "1",
        "bonusType": "",
        "id": "40",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "6",
        "grocery": "6",
        "retail": "0",
        "cardName": "American Express Hilton Honors",
        "bonus": "1250",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "6",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Hilton",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "12",
        "notes": "Bonus when spend $2,000 in 3 months; ",
        "total": "1",
        "bonusType": "",
        "id": "41",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "7",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Hilton Honors Aspire",
        "bonus": "1500",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "7",
        "affiliation": "Hilton",
        "cardType": "",
        "other": "7",
        "annualFee": "200",
        "lodging": "14",
        "notes": "Bonus when spend $4,000 in 3 months; $450 fee w/ $200 Hilton credit",
        "total": "3",
        "bonusType": "",
        "id": "42",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Gold Delta Skymiles",
        "bonus": "445",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Delta",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "0",
        "notes": "Bonus when spend $1,000 in 3 months; $95 fee waived first year",
        "total": "1",
        "bonusType": "",
        "id": "43",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Platinum Delta Skymiles",
        "bonus": "450",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Delta",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "0",
        "notes": "Bonus when spend $1,000 in 3 months; $195 fee offset by free companion flight; get MQM toward status",
        "total": "1",
        "bonusType": "",
        "id": "44",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Delta Reserve",
        "bonus": "400",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "Delta",
        "cardType": "",
        "other": "0",
        "annualFee": "255",
        "lodging": "0",
        "notes": "Bonus when spend $3,000 in 3 months; $450 fee offset by free companion flight; get MQM toward status",
        "total": "1",
        "bonusType": "",
        "id": "45",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Starwood Preffered Guest",
        "bonus": "750",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Starwood",
        "cardType": "",
        "other": "0",
        "annualFee": "0",
        "lodging": "6",
        "notes": "Bonus when spend $3,000 in 3 months; $95 fee offset by free night",
        "total": "2",
        "bonusType": "",
        "id": "46",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "3",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Starwood Preffered Guest Luxury",
        "bonus": "750",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "3",
        "affiliation": "Starwood",
        "cardType": "",
        "other": "0",
        "annualFee": "55",
        "lodging": "6",
        "notes": "Bonus when spend $3,000 in 3 months; $450 fee offset by $300 credit + free night",
        "total": "2",
        "bonusType": "",
        "id": "47",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "6",
        "retail": "0",
        "cardName": "American Express Blue Cash Preferred",
        "bonus": "200",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "3",
        "entertainment": "0",
        "air": "0",
        "affiliation": "American Express",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "0",
        "notes": "Bonus when spend $1,000 in 3 months; ",
        "total": "1",
        "bonusType": "",
        "id": "48",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "3",
        "retail": "0",
        "cardName": "American Express EveryDay Preferred",
        "bonus": "150",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "American Express",
        "cardType": "",
        "other": "0",
        "annualFee": "95",
        "lodging": "0",
        "notes": "Bonus when spend $1,000 in 3 months; points worth double when 30+ transactions in billing period",
        "total": "1",
        "bonusType": "",
        "id": "49",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "0",
        "retail": "0",
        "cardName": "American Express Green",
        "bonus": "95",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "0",
        "entertainment": "0",
        "air": "2",
        "affiliation": "American Express",
        "cardType": "",
        "other": "2",
        "annualFee": "95",
        "lodging": "2",
        "notes": "$95 annual fee waived first year",
        "total": "1",
        "bonusType": "",
        "id": "50",
        "bank": "",
        "multiplier": ""
    },
    {
        "dining": "0",
        "grocery": "2",
        "retail": "0",
        "cardName": "Wyndham Rewards Visa Signature",
        "bonus": "300",
        "hasAnnualFee": "1",
        "online": "0",
        "gas": "2",
        "entertainment": "0",
        "air": "0",
        "affiliation": "Wyndham",
        "cardType": "",
        "other": "0",
        "annualFee": "75",
        "lodging": "5",
        "notes": "Bonus when spend $1,000 in 3 months; ",
        "total": "1",
        "bonusType": "",
        "id": "51",
        "bank": "",
        "multiplier": ""
    }
]
export default cardsNoFee